# An explanation on each parameter can be found at https://docs.github.com/en/actions/using-workflows/about-workflows
name: CI 


on:
  pull_request:

jobs: 
     linting:
      name: Check Formatting
      runs-on: ubuntu-latest
      steps:
        #allows to run scripts against your code
        - name: checkout 
          uses: actions/checkout@v3

        #sets up poetry for package management
        - name: Install Poetry 
          run: |
            pipx install poetry 
        
        - name: Setup Python
          uses: actions/setup-python@v4 
          # Need to cache dependencies to use poetry  https://github.com/marketplace/actions/setup-python
          with: 
            python-version: '3.11'
            cache: 'poetry'

        - name: Install poetry dependencies
          run: |
             poetry install --only CI

        - name: Test format
          run: | 
            poetry run black --check .
          
      

          

          









      